language: node_js
dist: trusty
sudo: required

node_js:
  - "8"

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

install:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install python3; fi
  - npm install --unsafe-perm

script:
  - echo $TRAVIS_OS_NAME
  - python3 --version
  - node --version
  - npm --version
  - npm run lint
  - npm run dist
  - npm run test
  - npm run test:npm && echo 'Npm packing test is passed'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8c6e384e12876030529f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change

after_success:
  - npm run test:coverage

before_deploy:
  - npm version
  - npm run dist

deploy:
  provider: npm
  email: zixia@zixia.net
  api_key: "$NPM_TOKEN"
  skip_cleanup: true

