os:
  - linux
  - osx

language: node_js
node_js:
  - "9"
  - "10"

python: "3"

cache:
  directories:
    - models
    - node_modules
    - python3

before_install: # switch to python 3.6
  - python -c 'import sys; print(sys.version_info)'
  - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then source ~/virtualenv/python3.6/bin/activate; pip3 install -U pytest; fi
  - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++; fi
  # - if [ "$TRAVIS_OS_NAME" == 'osx' ];  then rvm get stable; fi
  # - if [ "$TRAVIS_OS_NAME" == 'osx' ];  then brew update; fi
  # - if [ "$TRAVIS_OS_NAME" == 'osx' ];  then brew install python3; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ];  then brew upgrade python; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ];  then brew install cairo pango libpng; fi
script:
  - echo TRAVIS_OS_NAME="$TRAVIS_OS_NAME"
  - python3 -c 'import sys; print(sys.version_info)'
  - node --version
  - npm --version
  - npm run test
after_success:
  - npm run test:coverage

stages:
  - test
  - pack
  - name: deploy
    if: (type = push) AND branch =~ ^(master|v\d+\.\d+)$

jobs:
  include:
    - stage: pack
      before_install: # switch to python 3.6
        - source ~/virtualenv/python3.6/bin/activate
        - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
      script:
        - ./scripts/generate-version.sh
        - npm run test:pack && echo 'Npm packing test is passed'

    - stage: deploy
      before_install: # switch to python 3.6
        - source ~/virtualenv/python3.6/bin/activate
        - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
      script:
        - echo 'Deploying to Docker Hub ...'
        - curl --silent -X POST -d '{"from":"travis"}' "$DOCKER_REBUILD_URL"
        - echo "Deploying to NPM ..."
        - npm version
        - ./scripts/generate-version.sh
        - ./scripts/package-publish-config-tag.sh
        - npm run dist

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8c6e384e12876030529f
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always

  email:
    on_success: change
    on_failure: change
    on_start: never
    on_cancel: never
    on_error: never
