language: node_js
node_js:
  - "7"
  - "8"

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: change
    on_start: never
    on_cancel: never
    on_error: never

stages:
  - test
  - pack
  - name: deploy
    if: branch = /^(master|v\d+\.\d+)/

jobs:
  include:
    - stage: test
      matrix:
        include:
          - os: linux
          - os: osx
      before_install: # switch to python 3.5
        - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then source ~/virtualenv/python3.5/bin/activate; fi
        - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++; fi
        - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then brew update; fi
        - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then brew install python3 pkg-config cairo pango libpng; fi # jpeg giflib
      script:
        - echo $TRAVIS_OS_NAME
        - python3 --version
        - node --version
        - npm --version
        - npm run test
      after_success:
        - npm run test:coverage

    - stage: pack
      before_install: # switch to python 3.5
        - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then source ~/virtualenv/python3.5/bin/activate; fi
        - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++; fi
        - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then brew update; fi
        - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then brew install python3 pkg-config cairo pango libpng; fi # jpeg giflib
      script:
        - npm run test:npm && echo 'Npm packing test is passed'

    - stage: deploy
      node_js: "8"
      before_install: # switch to python 3.5
        - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then source ~/virtualenv/python3.5/bin/activate; fi
        - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++; fi
        - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then brew update; fi
        - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then brew install python3 pkg-config cairo pango libpng; fi # jpeg giflib
      script:
        - echo "Deploying to NPM ..."
        - npm version
        - npm run dist

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"

    - stage: deploy
      node_js: "8"
      script:
        - echo 'Deploying to Docker Hub ...'
        - ./scripts/docker.sh deploy
