sudo: required
dist: trusty
language: node_js

node_js:
  - "7"
  - "8"

os:
  - linux
  - osx

cache:
  directories:
    - node_modules


install:
  - npm install
  - pip3 install -r requirements.txt

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - python3 --version
  - npm run lint
  - npm run dist
  - npm test
  - npm run test:npm && echo 'Npm packing test is passed'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8c6e384e12876030529f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change

after_success:
  - npm run coverage

before_deploy:
  - npm version
  - npm run dist

deploy:
  provider: npm
  email: zixia@zixia.net
  api_key: "$NPM_TOKEN"
  skip_cleanup: true

